Drop autoconf support.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,24 +1,88 @@
 #! /bin/sh
-cp -f VERSION cfg/autoconf/VERSION
-cd cfg/autoconf
-echo 'WARNING: configure support will be deprecated one time, consider switching to cmake'
-echo 'More information about cmake is available at <http://www.cmake.org>.'
-if [ ! -f ./configure -o "x$1" = "x--regenerate" -o ./configure.in -nt ./configure ] ; then
-    echo "Running autoconf..."
-    if ! type autoconf > /dev/null 2>&1 ; then
-        echo "Please install autoconf"
-        exit 1
-    fi
-    autoconf
-    test "x$1" = "x--regenerate" && shift
+# vim: expandtab sw=4 ts=4 sts=4:
+# Wrapper for cmake to keep minimal compatibility with auto*
+
+# Exit on error and undefined variables
+set -e -u
+
+cat <<EOT
+Wrapper script for configuring CMake for Gammu.
+
+This provides limited compatibility with configure, if you want full
+configuration control, use directly CMake. More information about CMake
+is available at <http://www.cmake.org>.
+
+EOT
+
+if ! type cmake > /dev/null 2>&1 ; then
+    echo 'ERROR: CMake not found, please install it, it is required for build.'
+    exit 1
 fi
-if ./configure "$@" ; then
-    if [ "$1" = "--help" ]
-    then
-        echo
-        echo "Use --regenerate as first parameter regenerate configure script"
-    else
-        mv -f Makefile.cfg ../Makefile.cfg
-        mv -f config.h ../config.h
-    fi
+
+help() {
+    cat <<EOT
+Usage: ./configure [options]
+
+--help|-h           shows this help
+--prefix=<path>     installation prefix
+--build-dir=<path>  (sub)directory where build will happen
+--enable-shared     enables shared build
+--enable-debug      enables debug build
+
+EOT
+    exit 2
+}
+
+# directory where we will build
+BUILD_DIR=build-configure
+
+# directory where sources are located
+SOURCE_DIR=`pwd`
+
+# cmake parameters
+CMAKE_PREFIX=
+CMAKE_SHARED=
+CMAKE_DEBUG=
+
+# process command line
+while [ "$#" -gt 0 ] ; do
+    case "$1" in
+        --help|-h)
+            help
+            ;;
+        --prefix=*)
+            CMAKE_PREFIX="-DCMAKE_INSTALL_PREFIX=\"`echo $1|sed 's/^--prefix=//'`\""
+            ;;
+        --build-dir=*)
+            BUILD_DIR="`echo $1|sed 's/^--prefix=//'`"
+            ;;
+        --enable-shared)
+            CMAKE_SHARED="-DENABLE_SHARED=ON"
+            ;;
+        --disable-shared)
+            CMAKE_SHARED="-DENABLE_SHARED=OFF"
+            ;;
+        --enable-debug)
+            CMAKE_DEBUG="-DCMAKE_BUILD_TYPE=\"Debug\""
+            ;;
+        --disable-debug)
+            CMAKE_DEBUG=
+            ;;
+        *)
+            echo 'Unknown parameter: $1'
+            help
+            ;;
+    esac
+    shift
+done
+
+# create build dir if needed
+if [ ! -d "$BUILD_DIR" ] ; then
+    mkdir -p "$BUILD_DIR"
 fi
+
+# go to build dir
+cd "$BUILD_DIR"
+
+# invoke cmake to do configuration
+cmake $SOURCE_DIR $CMAKE_PREFIX $CMAKE_SHARED $CMAKE_DEBUG
