Imported gammu 0.85.5

diff --git a/cfg/autoconf/configure.in b/cfg/autoconf/configure.in
--- a/cfg/autoconf/configure.in
+++ b/cfg/autoconf/configure.in
@@ -32,9 +32,8 @@ AC_PATH_PROG(INSTALL, install, no)
 AC_PATH_PROG(FIND, find, no)
 AC_PATH_PROG(RPMBUILD, rpmbuild)
 AC_PATH_PROG(RPMBUILD, rpm, no)
+AC_PATH_PROG(DOXYGEN, doxygen)
 
-dnl Checks for libraries.
-LDLIBS="$LDLIBS -lpthread"
 
 dnl Checks for library functions.
 AC_PROG_GCC_TRADITIONAL
@@ -42,7 +41,6 @@ AC_FUNC_MEMCMP
 AC_TYPE_SIGNAL
 AC_FUNC_VPRINTF
 AC_CHECK_FUNCS(scandir alphasort iswspace towlower)
-
 dnl Now this is checking is not used
 dnl AC_CHECK_FUNCS(mktime select socket strdup strerror strstr)
 dnl AC_SUBST(HAVE_SCANDIR)
@@ -50,10 +48,19 @@ dnl AC_SUBST(HAVE_ALPHASORT)
 
 dnl Checks for header files.
 AC_HEADER_STDC
-AC_CHECK_HEADERS(dirent.h mysql/mysql.h)
+AC_CHECK_HEADERS(dirent.h)
+AC_CHECK_HEADER(linux/irda.h,
+	[AC_DEFINE(HAVE_IRDA)
+	irda="yes"],
+	[irda="no"],
+	[#include <sys/socket.h>
+#include <linux/types.h>
+#include <sys/ioctl.h>])
 dnl This checking is not used now
+dnl AC_CHECK_HEADERS(mysql/mysql.h)
 dnl AC_CHECK_HEADERS(fcntl.h sys/file.h sys/ioctl.h sys/time.h unistd.h)
 dnl AC_SUBST(HAVE_DIRENT_H)
+
 
 dnl Checks for typedefs, structures, and compiler characteristics.
 AC_C_CONST
@@ -61,6 +68,212 @@ AC_TYPE_PID_T
 AC_TYPE_SIZE_T
 AC_HEADER_TIME
 AC_STRUCT_TM
+
+dnl -------------------------------------------------------------------------
+dnl based on
+dnl http://www.gnu.org/software/ac-archive/htmldoc/acx_pthread.html
+dnl
+AC_DEFUN([CHECK_PTHREAD], [
+AC_LANG_SAVE
+AC_LANG_C
+acx_pthread_ok=no
+
+# We used to check for pthread.h first, but this fails if pthread.h
+# requires special compiler flags (e.g. on True64 or Sequent).
+# It gets checked for in the link test anyway.
+
+# First of all, check if the user has set any of the PTHREAD_LIBS,
+# etcetera environment variables, and if threads linking works using
+# them:
+if test x"$PTHREAD_LIBS$PTHREAD_CFLAGS" != x; then
+        save_CFLAGS="$CFLAGS"
+        CFLAGS="$CFLAGS $PTHREAD_CFLAGS"
+        save_LIBS="$LIBS"
+        LIBS="$PTHREAD_LIBS $LIBS"
+        AC_MSG_CHECKING([for pthread_join in LIBS=$PTHREAD_LIBS with CFLAGS=$PTHREAD_CFLAGS])
+        AC_TRY_LINK_FUNC(pthread_join, acx_pthread_ok=yes)
+        AC_MSG_RESULT($acx_pthread_ok)
+        if test x"$acx_pthread_ok" = xno; then
+                PTHREAD_LIBS=""
+                PTHREAD_CFLAGS=""
+        fi
+        LIBS="$save_LIBS"
+        CFLAGS="$save_CFLAGS"
+fi
+# We must check for the threads library under a number of different
+# names; the ordering is very important because some systems
+# (e.g. DEC) have both -lpthread and -lpthreads, where one of the
+# libraries is broken (non-POSIX).
+
+# Create a list of thread flags to try.  Items starting with a "-" are
+# C compiler flags, and other items are library names, except for "none"
+# which indicates that we try without any flags at all.
+
+acx_pthread_flags="pthreads none -Kthread -kthread lthread -pthread -pthreads -mthreads pthread --thread-safe -mt"
+
+# The ordering *is* (sometimes) important.  Some notes on the
+# individual items follow:
+
+# pthreads: AIX (must check this before -lpthread)
+# none: in case threads are in libc; should be tried before -Kthread and
+#       other compiler flags to prevent continual compiler warnings
+# -Kthread: Sequent (threads in libc, but -Kthread needed for pthread.h)
+# -kthread: FreeBSD kernel threads (preferred to -pthread since SMP-able)
+# lthread: LinuxThreads port on FreeBSD (also preferred to -pthread)
+# -pthread: Linux/gcc (kernel threads), BSD/gcc (userland threads)
+# -pthreads: Solaris/gcc
+# -mthreads: Mingw32/gcc, Lynx/gcc
+# -mt: Sun Workshop C (may only link SunOS threads [-lthread], but it
+#      doesn't hurt to check since this sometimes defines pthreads too;
+#      also defines -D_REENTRANT)
+# pthread: Linux, etcetera
+# --thread-safe: KAI C++
+
+case "`uname -s`" in
+        *SunOS*)
+
+        # On Solaris (at least, for some versions), libc contains stubbed
+        # (non-functional) versions of the pthreads routines, so link-based
+        # tests will erroneously succeed.  (We need to link with -pthread or
+        # -lpthread.)  (The stubs are missing pthread_cleanup_push, or rather
+        # a function called by this macro, so we could check for that, but
+        # who knows whether they'll stub that too in a future libc.)  So,
+        # we'll just look for -pthreads and -lpthread first:
+
+        acx_pthread_flags="-pthread -pthreads pthread -mt $acx_pthread_flags"
+        ;;
+esac
+
+if test x"$acx_pthread_ok" = xno; then
+for flag in $acx_pthread_flags; do
+        case $flag in
+                none)
+                AC_MSG_CHECKING([whether pthreads work without any flags])
+                ;;
+
+                -*)
+                AC_MSG_CHECKING([whether pthreads work with $flag])
+                PTHREAD_CFLAGS="$flag"
+                ;;
+
+                *)
+                AC_MSG_CHECKING([for the pthreads library -l$flag])
+                PTHREAD_LIBS="-l$flag"
+                ;;
+        esac
+
+        save_LIBS="$LIBS"
+        save_CFLAGS="$CFLAGS"
+        LIBS="$PTHREAD_LIBS $LIBS"
+        CFLAGS="$CFLAGS $PTHREAD_CFLAGS"
+
+        # Check for various functions.  We must include pthread.h,
+        # since some functions may be macros.  (On the Sequent, we
+        # need a special flag -Kthread to make this header compile.)
+        # We check for pthread_join because it is in -lpthread on IRIX
+        # while pthread_create is in libc.  We check for pthread_attr_init
+        # due to DEC craziness with -lpthreads.  We check for
+        # pthread_cleanup_push because it is one of the few pthread
+        # functions on Solaris that doesn't have a non-functional libc stub.
+        # We try pthread_create on general principles.
+        AC_TRY_LINK([#include <pthread.h>],
+                    [pthread_t th; pthread_join(th, 0);
+                     pthread_attr_init(0); pthread_cleanup_push(0, 0);
+                     pthread_create(0,0,0,0); pthread_cleanup_pop(0); ],
+                    [acx_pthread_ok=yes])
+
+        LIBS="$save_LIBS"
+        CFLAGS="$save_CFLAGS"
+
+        AC_MSG_RESULT($acx_pthread_ok)
+        if test "x$acx_pthread_ok" = xyes; then
+                break;
+        fi
+
+        PTHREAD_LIBS=""
+        PTHREAD_CFLAGS=""
+done
+fi
+
+# Various other checks:
+if test "x$acx_pthread_ok" = xyes; then
+        save_LIBS="$LIBS"
+        LIBS="$PTHREAD_LIBS $LIBS"
+        save_CFLAGS="$CFLAGS"
+        CFLAGS="$CFLAGS $PTHREAD_CFLAGS"
+
+        # Detect AIX lossage: threads are created detached by default
+        # and the JOINABLE attribute has a nonstandard name (UNDETACHED).
+        AC_MSG_CHECKING([for joinable pthread attribute])
+        AC_TRY_LINK([#include <pthread.h>],
+                    [int attr=PTHREAD_CREATE_JOINABLE;],
+                    ok=PTHREAD_CREATE_JOINABLE, ok=unknown)
+        if test x"$ok" = xunknown; then
+                AC_TRY_LINK([#include <pthread.h>],
+                            [int attr=PTHREAD_CREATE_UNDETACHED;],
+                            ok=PTHREAD_CREATE_UNDETACHED, ok=unknown)
+        fi
+        if test x"$ok" != xPTHREAD_CREATE_JOINABLE; then
+                AC_DEFINE(PTHREAD_CREATE_JOINABLE, $ok,
+                          [Define to the necessary symbol if this constant
+                           uses a non-standard name on your system.])
+        fi
+        AC_MSG_RESULT(${ok})
+        if test x"$ok" = xunknown; then
+                AC_MSG_WARN([we do not know how to create joinable pthreads])
+        fi
+
+        AC_MSG_CHECKING([if more special flags are required for pthreads])
+        flag=no
+        case "`uname -s`" in
+                *AIX* | *FreeBSD*)     flag="-D_THREAD_SAFE";;
+                *SunOS* | *OSF* | *HP-UX*) flag="-D_REENTRANT";;
+        esac
+        AC_MSG_RESULT(${flag})
+        if test "x$flag" != xno; then
+                PTHREAD_CFLAGS="$flag $PTHREAD_CFLAGS"
+        fi
+
+        LIBS="$save_LIBS"
+        CFLAGS="$save_CFLAGS"
+
+        # More AIX lossage: must compile with cc_r
+        AC_CHECK_PROG(PTHREAD_CC, cc_r, cc_r, ${CC})
+else
+        PTHREAD_CC="$CC"
+fi
+
+AC_SUBST(PTHREAD_LIBS)
+AC_SUBST(PTHREAD_CFLAGS)
+AC_SUBST(PTHREAD_CC)
+
+# Finally, execute ACTION-IF-FOUND/ACTION-IF-NOT-FOUND:
+if test x"$acx_pthread_ok" = xyes; then
+        ifelse([$1],,AC_DEFINE(HAVE_PTHREAD,1,[Define if you have POSIX threads libraries and header files.]),[$1])
+        :
+else
+        acx_pthread_ok=no
+        $2
+fi
+AC_LANG_RESTORE
+])dnl CHECK_PTHREAD
+dnl -------------------------------------------------------------------------
+
+dnl Checks for libraries.
+CHECK_PTHREAD(
+	[AC_DEFINE(HAVE_PTHREAD)
+        pthread="yes"],
+	[echo "WARNING: pthread can not be used, searching disabled!"
+        pthread="no"])
+LDLIBS="$LDLIBS $PTHREAD_LIBS $PTHREAD_CFLAGS"
+CFLAGS="$CFLAGS $PTHREAD_CFLAGS"
+AC_CACHE_CHECK([for the Bluez Bluetooth stack], ac_cv_have_sockaddr_rc,
+     [AC_TRY_COMPILE([#include <sys/socket.h>
+          #include <bluetooth/bluetooth.h>
+          #include <bluetooth/rfcomm.h>],
+          [struct sockaddr_rc rc;],
+           ac_cv_have_sockaddr_rc=yes,
+               ac_cv_have_sockaddr_rc=no)])
 
 dnl doc directory
 DOC_DIR="$datadir/doc/gammu"
@@ -97,29 +310,28 @@ AC_ARG_WITH(rpmdir,
 	  else
 		RPM_DIR="$withval"
 	  fi
-	],
-    [
-        if test -r /usr/lib/rpm/macros  ; then
-            get_rpm_var() {
-            VALUE=$(grep -s "^%$1[[[:space:]]]" ~/.rpmmacros /usr/lib/rpm/macros | head -n 1 | awk '{print $2}')
-            if test -z "$VALUE"  ; then
-                exit 1
-            fi
+	],[
+		if test -r /usr/lib/rpm/macros  ; then
+			get_rpm_var() {
+			VALUE=$(grep -s "^%$1[[[:space:]]]" ~/.rpmmacros /usr/lib/rpm/macros | head -n 1 | awk '{print $2}')
+			if test -z "$VALUE"  ; then
+				exit 1
+			fi
 
-            while echo "$VALUE" | grep -q '%' ; do
-                VAR=$(echo "$VALUE" | sed 's/^[[^%]]*%{\([[^}]]*\)}.*$/\1/')
-                REPL=$(get_rpm_var "$VAR")
-                VALUE=$(echo "$VALUE" | sed "s@%{$VAR}@$REPL@")
-            done
-            echo $VALUE
-            }
+			while echo "$VALUE" | grep -q '%' ; do
+			VAR=$(echo "$VALUE" | sed 's/^[[^%]]*%{\([[^}]]*\)}.*$/\1/')
+			REPL=$(get_rpm_var "$VAR")
+			VALUE=$(echo "$VALUE" | sed "s@%{$VAR}@$REPL@")
+		done
+		echo $VALUE
+		}
 
-            VALUE=$(get_rpm_var _topdir)
-            if test ! -z "$VALUE"  ; then
-                RPM_DIR="$VALUE"
-            fi
-        fi
-    ]
+		VALUE=$(get_rpm_var _topdir)
+		if test ! -z "$VALUE"  ; then
+			RPM_DIR="$VALUE"
+		fi
+		fi
+	]
 )
 AC_SUBST(RPM_DIR)
 
@@ -197,29 +409,30 @@ AC_ARG_ENABLE(irdaphonet,
 	[  --disable-irdaphonet    Disable NOKIA PHONET FBUS over irda sockets
 	                  (all new Nokia)],
 	[gsm_enable_irdaphonet="no"],
-	[AC_CHECK_HEADER(linux/irda.h,
-		[AC_DEFINE(GSM_ENABLE_IRDAPHONET) gsm_enable_irdaphonet="yes"],
-		[gsm_enable_irdaphonet="no"])])
+	[if test $irda = yes ; then
+		AC_DEFINE(GSM_ENABLE_IRDAPHONET)
+		gsm_enable_irdaphonet="yes"
+	 else
+		gsm_enable_irdaphonet="no"
+	 fi])
 AC_ARG_ENABLE(irdaat,
 	[  --disable-irdaat        Disable AT commands over irda sockets],
 	[gsm_enable_irdaat="no"],
-	[AC_CHECK_HEADER(linux/irda.h,
-		[AC_DEFINE(GSM_ENABLE_IRDAAT) gsm_enable_irdaat="yes"],
-		[gsm_enable_irdaat="no"])])
+	[if test $irda = yes ; then
+		AC_DEFINE(GSM_ENABLE_IRDAAT)
+		gsm_enable_irdaat="yes"
+	 else
+		gsm_enable_irdaat="no"
+	 fi])
 AC_ARG_ENABLE(irdaobex,
 	[  --disable-irdaobex      Disable OBEX over irda sockets],
 	[gsm_enable_irdaobex="no"],
-	[AC_CHECK_HEADER(linux/irda.h,
-		[AC_DEFINE(GSM_ENABLE_IRDAOBEX) gsm_enable_irdaobex="yes"],
-		[gsm_enable_irdaobex="no"])])
-
-AC_CACHE_CHECK([for the Bluez Bluetooth stack], ac_cv_have_sockaddr_rc,
-     [AC_TRY_COMPILE([#include <sys/socket.h>
-          #include <bluetooth/bluetooth.h>
-          #include <bluetooth/rfcomm.h>],
-          [struct sockaddr_rc rc;],
-           ac_cv_have_sockaddr_rc=yes,
-               ac_cv_have_sockaddr_rc=no)])
+	[if test $irda = yes ; then
+		AC_DEFINE(GSM_ENABLE_IRDAOBEX)
+		gsm_enable_irdaobex="yes"
+	 else
+		gsm_enable_irdaobex="no"
+	 fi])
 AC_ARG_ENABLE(bluefbus,
 	[  --disable-bluefbus      Disable Nokia FBUS2 over Bluetooth stack
                           (Nokia 6210)],
@@ -227,7 +440,9 @@ AC_ARG_ENABLE(bluefbus,
 	[if test $ac_cv_have_sockaddr_rc = yes; then
 		AC_DEFINE(GSM_ENABLE_BLUEFBUS2)
 		gsm_enable_bluefbus2="yes"
-		LDLIBS="$LDLIBS -lbluetooth"
+		if ( echo $LDLIBS | grep -v -q -e -lbluetooth ) ; then
+			LDLIBS="$LDLIBS -lbluetooth"
+		fi
 	  else
 		gsm_enable_bluefbus2="no"
 	  fi])
@@ -238,7 +453,9 @@ AC_ARG_ENABLE(bluephonet,
 	[if test $ac_cv_have_sockaddr_rc = yes; then
 		AC_DEFINE(GSM_ENABLE_BLUEPHONET)
 		gsm_enable_bluephonet="yes"
-		LDLIBS="$LDLIBS -lbluetooth"
+		if ( echo $LDLIBS | grep -v -q -e -lbluetooth ) ; then
+			LDLIBS="$LDLIBS -lbluetooth"
+		fi
 	  else
 		gsm_enable_bluephonet="no"
 	  fi])
@@ -248,7 +465,9 @@ AC_ARG_ENABLE(blueat,
 	[if test $ac_cv_have_sockaddr_rc = yes; then
 		AC_DEFINE(GSM_ENABLE_BLUEAT)
 		gsm_enable_blueat="yes"
-		LDLIBS="$LDLIBS -lbluetooth"
+		if ( echo $LDLIBS | grep -v -q -e -lbluetooth ) ; then
+			LDLIBS="$LDLIBS -lbluetooth"
+		fi
 	  else
 		gsm_enable_blueat="no"
 	  fi])	
@@ -258,7 +477,9 @@ AC_ARG_ENABLE(blueobex,
 	[if test $ac_cv_have_sockaddr_rc = yes; then
 		AC_DEFINE(GSM_ENABLE_BLUEOBEX)
 		gsm_enable_blueobex="yes"
-		LDLIBS="$LDLIBS -lbluetooth"
+		if ( echo $LDLIBS | grep -v -q -e -lbluetooth ) ; then
+			LDLIBS="$LDLIBS -lbluetooth"
+		fi
 	  else
 		gsm_enable_blueobex="no"
 	  fi])	
@@ -329,6 +550,8 @@ AC_SUBST(LDLIBS)
 dnl Writing output files
 AC_CONFIG_HEADER(config.h)
 AC_OUTPUT(Makefile.cfg
+	  ../pkgconfig/gammu.pc
+	  ../doxygen/Doxyfile
 	  ../rpm/gammu.spec
 	  ../../gammu/msvc6.mak/gammu.rc
 	  ../../gammu/msvc7.mak/gammu.rc
@@ -362,6 +585,7 @@ echo "
   Debug                                         - $debug
   CB messages                                   - $gsm_enable_cellbroadcast
   Backup functions                              - $gsm_enable_backup
+  Searching phones (requires pthread)           - $pthread
 
   Phone protocols
   ---------------
